# Test a trained model
Once you have trained a model, you can test it with the test data you put aside

We will start by rerunning the code from the previous notebook to create a trained model

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from pathlib import Path
newfile=Path.joinpath(Path.cwd().parent,'CSV_files/lots_of_flight_data.csv')
delays_df=pd.read_csv(newfile)
delays_df.dropna(inplace=True)
delays_df.drop_duplicates(inplace=True)
X=delays_df.loc[:,['DISTANCE','CRS_ELAPSED_TIME']]
y=delays_df.loc[:,['ARR_DELAY']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=20)
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [4]:
y_pred=regressor.predict(X_test)
y_pred

array([[ 2.27668693],
       [-1.1565955 ],
       [ 2.3698648 ],
       [ 6.13441272],
       [-1.37345855],
       [ 0.68704272],
       [ 9.46689046],
       [-3.50425721],
       [21.22873221],
       [ 7.34371863],
       [-1.1565955 ],
       [-3.78544672],
       [-1.68846721],
       [-1.72494544],
       [ 2.3698648 ],
       [ 2.36223797],
       [ 5.25105412],
       [ 2.43253535],
       [-3.74896848],
       [-3.50425721],
       [-5.56475848],
       [ 2.5485937 ],
       [-3.50425721],
       [ 0.12135187],
       [-3.12060709],
       [13.60911759],
       [21.22873221],
       [-0.66285794],
       [ 0.21618565],
       [11.01840051]])

In [5]:
y_test

    ARR_DELAY
71          7
75          8
2         -13
83         -1
46         -7
49        -19
14         16
38         -9
0         -17
50         13
72         -7
94        -15
89         -6
93         27
5         -16
78         -4
25         47
90        -15
88        -20
40        -14
39        -18
52        -17
37        -14
66         18
33         -2
23        -13
1         -25
96         -8
70          0
21        232